name: Check editorconfig

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check-editorconfig:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 1
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24

      - name: Validate the project's own .editorconfig
        run: npx --yes @sheplu/editorconfig --mode check
